version: "0.2"
ignorePaths:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/.turbo/**"
  - "**/.cache/**"
  - pnpm-lock.yaml
  - "**/package.json"
  - "**/.git/**"
  - "**/coverage/**"
  - "**/*.min.js"
  - "**/*.map"
  - "**/turbo.json"
  - "**/pnpm-workspace.yaml"
  - packages/db/drizzle/schema.ts
  - code-rabbit-ai.yaml
  - .env*
  - .vscode/**
  - LICENSE
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - html
  - css
  - bash
  - npm
  - filetypes
  - python
  - markdown
  - lorem-ipsum
words:
  - actioncable
  - adbanner
  - adsbygoogle
  - adsense
  - adtest
  - alola
  - battlestadium
  - blooddmoon
  - Bloodmoon
  - bulu
  - checkin
  - cmdk
  - Embla
  - galar
  - gmax
  - hearthflame
  - hoenn
  - ianvs
  - johto
  - kalos
  - kanto
  - koko
  - lele
  - limitlesstcg
  - lintstaged
  - Magnifer
  - maushold
  - Metagame
  - nativewind
  - navuser
  - neondatabase
  - nums
  - orgheader
  - paldea
  - pkmn
  - pokedex
  - pokepast
  - pokepaste
  - Pressable
  - randompic
  - scrollback
  - serviceworker
  - shadcn
  - sidebarfooter
  - sidebarheader
  - sinnoh
  - slotnumber
  - Sonner
  - sqlstring
  - tatsugiri
  - teamlists
  - teamsheet
  - Tera
  - terastal
  - thatguyinabeanie
  - tseslint
  - Turborepo
  - typesafe
  - unova
  - UNPOOLED
  - Unreads
  - uploadthing
  - Ursaluna
  - UTSSR
  - vaul
ignoreWords: []
import: []
