packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^20
  "@clerk/backend": "^1"
  "@clerk/clerk-react": "^5"
  "@clerk/nextjs": "^6"
  "@auth/core": ^0
  "@tanstack/react-query": ^5
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next
  "@t3-oss/env-nextjs": ^0
  "@tanstack/react-table": ^8
  eslint: ^9
  next: ^15
  prettier: ^3
  tailwindcss: ^3
  typescript: ^5
  zod: ^3

catalogs:
  react18:
    react: ^18
    react-dom: ^18
    "@types/react": ^18
    "@types/react-dom": ^18
  react19:
    react: rc
    react-dom: rc
    "@types/react": rc
    "@types/react-dom": rc
