packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^20
  "@tanstack/react-query": ^5
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next

  "@tanstack/react-table": ^8
  "tailwind-merge": ^2
  "tailwindcss-animate": ^1
  "tailwind-variants": ^0
  eslint: ^9
  postcss: ^8
  prettier: ^3
  tailwindcss: ^3
  typescript: ^5
  zod: ^3
  superjson: ^2

catalogs:
  auth:
    "@auth/core": ^0
    "@auth/drizzle-adapter": ^1
    "@clerk/backend": "^1"
    "@clerk/clerk-react": "^5"
    "@clerk/nextjs": "^6"
    jose: ^5
    "js-cookie": ^3
    cookie: ^1
    "@types/js-cookie": ^3

  next:
    "@next/third-parties": ^15
    next: canary
    "@types/node": ^20
    "@t3-oss/env-nextjs": ^0

  react18:
    react: ^18
    react-dom: ^18
    "@types/react": ^18
    "@types/react-dom": ^18

  react19:
    react: rc
    react-dom: rc
    "@types/react": rc
    "@types/react-dom": rc

  turbo:
    turbo: ^2
    "@turbo/gen": ^2
