packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^20
  eslint: ^9
  postcss: ^8
  prettier: ^3
  typescript: ^5
  zod: ^3
  superjson: ^2

catalogs:
  auth:
    "@auth/core": ^0
    "@auth/drizzle-adapter": ^1
    "@clerk/backend": ^1
    "@clerk/clerk-react": ^5
    "@clerk/nextjs": "^6"
    jose: ^5
    "js-cookie": ^3
    cookie: ^1
    "@types/js-cookie": ^3

  babel:
    "@babel/core": ^7
    "@babel/preset-env": ^7
    "@babel/runtime": ^7
    "@types/babel__core": ^7

  db:
    "drizzle-orm": ^0
    "drizzle-typebox": ^0
    "drizzle-zod": ^0
    "drizzle-kit": ^0
    "@neondatabase/serverless": ^0
    "postgres": ^3

  expo:
    "@expo/metro-config": ^0
    "expo": ^52
    "expo-constants": ^17
    "expo-dev-client": ^5
    "expo-linking": ^7
    "expo-router": ^4
    "expo-secure-store": ^14
    "expo-splash-screen": ^0.29
    "expo-status-bar": ^2
    "expo-web-browser": ^14

  next:
    next: canary
    "@next/third-parties": canary
    "@next/eslint-plugin-next": canary
    "@types/node": ^20
    "@t3-oss/env-nextjs": ^0

  react:
    react: ^18
    react-dom: ^18
    "@types/react": ^18
    "@types/react-dom": ^18

  react19:
    react: rc
    react-dom: rc
    "@types/react": rc
    "@types/react-dom": rc

  react-native:
    "react-native": ^0.76
    "react-native-css-interop": ^0.0.36
    "react-native-gesture-handler": ^2
    "react-native-reanimated": ^3
    "react-native-safe-area-context": ^4
    "react-native-screens": ^4

  tailwind:
    "tailwind-merge": ^2
    "tailwindcss-animate": ^1
    "tailwind-variants": ^0
    tailwindcss: ^3
    nativewind: ^4

  tanstack:
    "@tanstack/react-query": ^5
    "@tanstack/react-table": ^8
    "@tanstack/react-query-devtools": ^5

  trpc:
    "@trpc/client": next
    "@trpc/react-query": next
    "@trpc/server": next
    "@trpc/next": next

  turbo:
    turbo: ^2
    "@turbo/gen": ^2

  vercel:
    "@vercel/analytics": ^1
    "@vercel/flags": ^2
    "@vercel/functions": ^1
    "@vercel/kv": ^3
    "@vercel/speed-insights": ^1
